### ISSUE TITLE
Onde está o código?!

### ISSUE THREAD

**Issue by thiagopbueno** [herrmann/jasdd#1]
Oi Herrmann, tudo bem?

Sou aluno da Leliane. Acabo de ler o teu artigo do Bracis13 e fiquei bastante interessado.
Teria como vc disponibilizar o teu código aqui no repositório?

[]s

**Comment by felipessalvatore** [comment]
Cade?

**Comment by herrmann** [comment]
Oi, não estava acompanhando as issues aqui... vou migrar o repositório pra cá hoje à noite. []'s

**Comment by vibonadia** [comment]
Ebaa :+1: :+1: :+1:
